#pragma once
#include "CoreMinimal.h"
#include "e_auto_pad_type.generated.h"

UENUM()
enum class e_auto_pad_type : uint32 {
    none,
    nop,
    wait_playable,
    random,
    random_no_move,
    random_enemy,
    target_pos,
    target_pos_enemy,
    target_pos_random,
    target_pos_path,
    ui_button,
    renda_no_move,
    renda_no_move_decide,
    renda_move,
    renda_move_decide,
    random_no_button,
    target_pos_zone,
    target_pos_zone_radius,
    target_pos_zone_radius_no_button,
    ui_button_select_index,
    ui_button_select_item,
    ui_button_itemget,
    ui_button_force,
    ui_button_pause_boot,
    ui_button_force_decide,
    ui_button_force_cancel,
    force_pad_left_stick,
    force_pad_right_stick,
    mg_base,
    mg_mahjong,
    mg_karaoke,
    mg_shogi,
    mg_hanafuda,
    mg_oichokabu,
    mg_poker,
    mg_fishing,
    mg_nichibu,
    mg_kakashi,
    mg_taishi,
    mg_togi,
    mg_drinking,
    mg_jangkeng,
    mg_sexy_phase,
    mg_udon,
    mg_kyoukei,
    mg_tintiro,
    mg_chohan,
    mg_taihou,
    mg_makiwari,
    mg_cooking,
    max,
};

