#pragma once
#include "CoreMinimal.h"
#include "EAnotherMainMenuUI.generated.h"

UENUM(BlueprintType)
enum class EAnotherMainMenuUI : uint8 {
    FadeIn_Bg00,
    FadeIn_List,
    FadeIn_ListP,
    FadeIn_SelPauseHeadAsc00_1,
    FadeIn_SelPauseHeadAsc00_2,
    FadeIn_SelPauseHeadAsc00_3,
    FadeIn_PauseHeadAsc00_1,
    FadeIn_PauseHeadAsc00_2,
    FadeIn_PauseHeadAsc00_3,
    FadeOut_Bg00,
    FadeOut_List,
    FadeOut_ListP,
    FadeOut_SelPauseHeadAsc00_1,
    FadeOut_SelPauseHeadAsc00_2,
    FadeOut_SelPauseHeadAsc00_3,
    FadeOut_PauseHeadAsc00_1,
    FadeOut_PauseHeadAsc00_2,
    FadeOut_PauseHeadAsc00_3,
    SetTitle_FishingRod,
    SetTitle_PoultryFarm,
    SetTitle_CarBed,
    SetTitle_DogHouseLv,
    SetTitle_CookWare,
    SetTitle_Interior,
    SetState_FishingRod,
    SetState_PoultryFarm,
    SetState_CarBed,
    SetState_DogHouseLv,
    SetState_CookWare,
    SetState_Interior,
    SetPetNameD00,
    SetPetNameD01,
    SetPetNameD02,
    SetPetNameC00,
    SetPetNameC01,
    SetPetNameC02,
    SetPetTextureD00,
    SetPetTextureD01,
    SetPetTextureD02,
    SetPetTextureC00,
    SetPetTextureC01,
    SetPetTextureC02,
    SetBgTexture,
    SetBgHarukaTexture,
    UpdateCursol,
    HarukaGaugeFadeIn,
    HarukaGaugeFadeOut,
    UpdateHarukaGauge,
    UpdateHarukaRank,
    SetHarukaTexture,
    Max,
};

