#pragma once
#include "CoreMinimal.h"
#include "EFacePatternType.generated.h"

UENUM(BlueprintType)
enum class EFacePatternType : uint8 {
    invalid,
    pat_anger1,
    pat_anger2,
    pat_sad1,
    pat_sad2,
    pat_surp1,
    pat_pain1,
    pat_non1,
    pat_joy1,
    pat_joy2,
    pat_dead1,
    pat_dead2,
    pat_dead3,
    pat_scared1,
    pat_annoyance1,
    pat_think1,
    pat_think2,
    oneshot_attack1,
    oneshot_attack2,
    oneshot_attack3,
    oneshot_pain1,
    oneshot_joy1,
    oneshot_sad1,
    oneshot_anger1,
    oneshot_surp1,
    oneshot_shout1,
    hit_left1,
    hit_left2,
    hit_left3,
    hit_right1,
    hit_right2,
    hit_right3,
    hit_up1,
    hit_up2,
    hit_up3,
    hit_down1,
    hit_down2,
    hit_down3,
    hit_vomit1,
    hit_vomit2,
    pat_eye_nml,
    pat_eye_wink,
    Num,
    OFF = Num,
    Wait,
};

