#pragma once
#include "CoreMinimal.h"
#include "eFukubikiSequence.generated.h"

UENUM(BlueprintType)
enum eFukubikiSequence {
    eFUKUBIKI_SEQUENCE_INITIALIZE,
    eFUKUBIKI_SEQUENCE_LOAD_WAIT,
    eFUKUBIKI_SEQUENCE_LOTTERY,
    eFUKUBIKI_SEQUENCE_PLAY_ROTATE_START,
    eFUKUBIKI_SEQUENCE_PLAY_ROTATE,
    eFUKUBIKI_SEQUENCE_EJECT_BALL,
    eFUKUBIKI_SEQUENCE_BALL_MOT_WAIT,
    eFUKUBIKI_SEQUENCE_BALL_UPVIEW,
    eFUKUBIKI_SEQUENCE_PRESENT,
    eFUKUBIKI_SEQUENCE_PRESENT_WAIT,
    eFUKUBIKI_SEQUENCE_TICKET_CHECK,
    eFUKUBIKI_SEQUENCE_FINISH,
    eFUKUBIKI_SEQUENCE_MESSAGE_WAIT,
    eFUKUBIKI_SEQUENCE_CANCEL_WAIT,
};

