#pragma once
#include "CoreMinimal.h"
#include "eMONEYTYPE.generated.h"

UENUM(BlueprintType)
enum eMONEYTYPE {
    eMONEYTYPE_MONEY,
    eMONEYTYPE_MONEY_RUISEKI,
    eMONEYTYPE_RESERVED02,
    eMONEYTYPE_RESERVED03,
    eMONEYTYPE_TEN,
    eMONEYTYPE_TEN_RUISEKI,
    eMONEYTYPE_MJ,
    eMONEYTYPE_SHOGI_POINT,
    eMONEYTYPE_RESERVED08,
    eMONEYTYPE_RESERVED09,
    eMONEYTYPE_TOUGIJO,
    eMONEYTYPE_VITA,
    eMONEYTYPE_VIRTUE,
    eMONEYTYPE_VIRTUE_TOTAL,
    eMONEYTYPE_MONEY_USE_RUIKEI,
    eMONEYTYPE_FUKUBIKI_TICKET,
    eMONEYTYPE_COMMERCE_GAIN,
    eMONEYTYPE_RESERVED17,
    eMONEYTYPE_RESERVED18,
    eMONEYTYPE_RESERVED19,
    eMONEYTYPE_RESERVED20,
    eMONEYTYPE_RESERVED21,
    eMONEYTYPE_RESERVED22,
    eMONEYTYPE_RESERVED23,
    eMONEYTYPE_NUM,
};

