#pragma once
#include "CoreMinimal.h"
#include "EPokerGameState.generated.h"

UENUM(BlueprintType)
enum class EPokerGameState : uint8 {
    PreparationGameStart,
    SetMode,
    SetRule,
    SetStructure,
    SetComputer,
    SetupGame,
    OpeningMsg,
    DistributionCard,
    Discard,
    GameStart,
    PreparationRound,
    Action,
    ActionComputer,
    ActionPlayer,
    CheckRound,
    RoundEnd,
    OpenCards,
    ShowDown,
    Result,
    CollectingWinner,
    SelectContinueOrEnd,
    ChangeComputer,
    NoticeNoEffectItem,
    NoticeLuckUp,
    SelectHelpMenu,
    SelectItem,
    ForceGameEnd,
    GameEnd,
    WaitGameEnd,
    SankakuRule,
    SankakuRuleWait,
    TutorialPreparation,
    TutorialPrevDiscardMsg,
    TutorialPostDiscard,
    TutorialRoundBegin,
    TutorialRoundEnd,
    TutorialPrevActionPlayer,
    TutorialPostActionPlayer,
    TutorialPrevActionComputer,
    TutorialPostActionComputer,
    TutorialEndMsg,
    Max,
};

