#pragma once
#include "CoreMinimal.h"
#include "ERyouriUI.generated.h"

UENUM(BlueprintType)
enum class ERyouriUI : uint8 {
    OdaiC_FadeIn,
    OdaiC_FadeOut,
    OdaiC_Update,
    OdaiU_FadeIn,
    OdaiU_FadeOut,
    KiryuLine_FadeIn,
    KiryuLine_FadeOut,
    KiryuIcon_Hocho_FadaIn,
    KiryuIcon_Hocho_FadaOut,
    YakuButton_FadeIn,
    YakuButton_FadeOut,
    KanatuButton_FadeIn,
    KanatuButton_FadeOut,
    ChoumiBar_FadeIn,
    ChoumiBar_FadeOut,
    ChoumiButton_FadeIn,
    ChoumiButton_FadeOut,
    ChoumiEffect_FadeIn,
    ChoumiEffect_FadeOut,
    Oneshot_YakuEffect,
    Oneshot_KanetuEffect,
    Oneshot_Yoi,
    Oneshot_Imaichi,
    KiruBar_FadeIn,
    KiruBar_FadeOut,
    KiruHocho_Init,
    KiruHocho_Update,
    KiruHocho_Fin,
    KiruButton_Push,
    Houcho_Cut,
    ChoumiBar_Update,
    ChoumiBar_JustEffectPlay,
    UpdateOdaiC,
    UpdateOdaiC_Color,
    UpdateOdaiU,
    ChoumiBarSuji_Update,
    Update_YakuButtonType,
    Update_KanetsuButtonType,
    Update_ChoumiButtonType,
    UpdateChoumiRange,
    Max,
};

