#pragma once
#include "CoreMinimal.h"
#include "ESurfaceType.generated.h"

UENUM(BlueprintType)
enum class ESurfaceType : uint8 {
    Default,
    FloorMin,
    FloorStone = FloorMin,
    FloorWood,
    FloorCarpet,
    FloorCarpetLong,
    FloorMetal,
    FloorDirt,
    FloorGravel,
    FloorSea,
    FloorGrass,
    FloorTatami,
    FloorWire,
    FloorSand,
    FloorLawn,
    FloorBath,
    FloorBed,
    FloorDirtSoft,
    FloorTatamiNoShoes,
    FloorFlooringNoShoes,
    FloorCarpetNoShoes,
    FloorCushionNoShoes,
    FloorRedClay,
    FloorRiver,
    FloorWaterHole,
    FloorQuickDeath,
    FloorSp001,
    FloorSp002,
    FloorSp003,
    FloorDryDirt,
    FloorWetDirt,
    FloorStonePath,
    FloorRock,
    FloorBoard,
    FloorOldBoard,
    FloorDeadLeaf,
    FloorKawara,
    FloorMax,
    WallMin = FloorMax,
    WallTree = FloorMax,
    WallWallPaper,
    WallMetal,
    WallCloth,
    WallShoji,
    WallFusuma,
    WallGrass,
    WallMulti,
    WallBush,
    WallRock,
    WallSnow,
    WallMortar,
    WallWanderer,
    WallArms,
    WallMax,
    StairMin = WallMax,
    StairStone = WallMax,
    StairWood,
    StairDirt,
    StairWoodNoShoes,
    StairMax,
    Max = StairMax,
};

