#pragma once
#include "CoreMinimal.h"
#include "eTINTIRO_DEBUG_POS.generated.h"

UENUM(BlueprintType)
enum class eTINTIRO_DEBUG_POS : uint8 {
    TINTIRO_DEBUG_POS_NONE,
    TINTIRO_DEBUG_POS_DRAW,
    TINTIRO_DEBUG_POS_DICE,
    TINTIRO_DEBUG_POS_DICE0,
    TINTIRO_DEBUG_POS_DICE1,
    TINTIRO_DEBUG_POS_DICE2,
    TINTIRO_DEBUG_POS_DEME_MESSAGE,
    TINTIRO_DEBUG_POS_RATE,
    TINTIRO_DEBUG_POS_KICK_END,
    TINTIRO_DEBUG_POS_ADJ_BET,
    TINTIRO_DEBUT_POS_ADJ_WAIT,
    TINTIRO_DEBUG_POS_ADJ_WAIT_ALL,
    TINTIRO_DEBUG_POS_BET_SND,
    TINTIRO_DEBUG_POS_SELECT_PAUSE,
    TINTIRO_DEBUG_POS_DICE_VELO,
    TINTIRO_DEBUG_POS_DICE_ROT,
    TINTIRO_DEBUG_POS_DICE_MASS,
    TINTIRO_DEBUG_POS_DICE_FRIC,
    TINTIRO_DEBUG_POS_DICE_REST,
    TINTIRO_DEBUG_POS_VIB_SMALL,
    TINTIRO_DEBUG_POS_VIB_BIG,
    TINTIRO_DEBUG_POS_SHONBEN,
    TINTIRO_DEBUG_POS_NUM,
};

