#pragma once
#include "CoreMinimal.h"
#include "EUIColorPreset.generated.h"

UENUM(BlueprintType)
enum class EUIColorPreset : uint8 {
    DEFAULT,
    OFF,
    SEL,
    SELECTED,
    FORBID,
    TALK_KIRYU,
    KEYWORD_PINK,
    GET_ITEM,
    GET_WAZA,
    BLACK,
    GRAY,
    GREEN,
    BROWN,
    LIGHT_YELLOW,
    LIGHT_BLUE,
    LIGHT_GREEN,
    BLUE_GRAY,
    LIGHT_GRAY,
    SPEC,
    COMP,
    DECO_BROWN,
    COMMON_DECIDE,
    BG_KIRYU,
    BG_AKIYAMA,
    BG_SAEJIMA,
    BG_TANIMURA,
    BG_KI_MEISHI,
    TALK_HARUKA,
    MG_KARAOKE,
    KYABAMENU_HUKA,
    KYABAPRESENT_HUKA,
    SHOP_MENUNAME,
    SHOP_SP,
    SHOP_SP_HUKA,
    SANKAKU,
    SHIKAKU,
    BATSU,
    MARU,
    BLUE,
    PINK,
    Reserved00,
    Reserved01,
    Reserved02,
    Reserved03,
    Reserved04,
    Reserved05,
    Reserved06,
    Reserved07,
    Reserved08,
    Reserved09,
    Reserved10,
    Reserved11,
    Reserved12,
    Reserved13,
    Reserved14,
    Reserved15,
    Reserved16,
    Reserved17,
    Reserved18,
    Reserved19,
};

