#pragma once
#include "CoreMinimal.h"
#include "EUIShogiEnemyName.generated.h"

UENUM(BlueprintType)
enum class EUIShogiEnemyName : uint8 {
    Juubee,
    Kousaku,
    Kyuutarou,
    Yoichi,
    Kitahati,
    Masayoshi,
    Densiti,
    Saizou,
    Kumaroku,
    Kogenta,
    Goemon,
    Sasuke,
    Koushirou,
    Kenshin,
    Saburouta,
    Kunimatsu,
    Yazirou,
    Tsuruhei,
    Ichinosuke,
    Kameyoshi,
    Kakunoshin,
    Umon,
    Musamasa,
    Sukezaburou,
    Kongou,
    Sakyou,
    Kotetsu,
    Onimaru,
    Kokuunnsai,
    Karasutengu,
    Mikogami,
    ShougiMaster,
    Touha_One,
    Touha_Two,
    Touha_Three,
    Touha_Four,
    Touha_Five,
    Touha_Six,
    Touha_Seven,
    Touha_Eight,
    Touha_Nine,
    Touha_Ten,
    Touha_Last,
};

