#pragma once
#include "CoreMinimal.h"
#include "UIDataHanafudaDelegateYakuDescriptionUIAnimEndOfPlaybackDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FUIDataHanafudaDelegateYakuDescriptionUIAnimEndOfPlayback);

