#pragma once
#include "CoreMinimal.h"
#include "UIDataHanafudaDelegateRuleDescriptionUIAnimEndOfPlaybackDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FUIDataHanafudaDelegateRuleDescriptionUIAnimEndOfPlayback);

